/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academy_football_systeme;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author fcss
 */
public class Coach_Mengament extends javax.swing.JFrame {
DefaultTableModel dm;
    /**
     * Creates new form Coach_Mengament
     */
    public Coach_Mengament() {
        initComponents();
         this.setLocationRelativeTo(null);// center form in the screen
         ImageIcon ic= new ImageIcon("C:\\Users\\fcss\\Desktop\\projet_gui\\Academy_Football_Systeme\\src\\academy_football_systeme\\soccer_ball_26px.png");
     this.setIconImage(ic.getImage());
      this.setTitle("Coach Mengament");
      
      
      
      Connection con = null;
String url ="jdbc:sqlserver://localhost:1433;databaseName=academy_football_systeme;integratedSecurity=true;";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Coach_Mengament.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            con =DriverManager.getConnection(url);
            if(con!=null)
            {
                                        String query="select * from Coach ";
                         
                         Statement st = con.createStatement();
ResultSet rs = st.executeQuery(query);
                         
        dm = (DefaultTableModel) C_Jtable.getModel();
        dm.setRowCount(0);
        while(rs.next())
        {
        dm.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),rs.getString(6),rs.getString(7)});
        }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Coach_Mengament.class.getName()).log(Level.SEVERE, null, ex);
        }
      
  
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EC_B = new javax.swing.JButton();
        AC_B = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        C_Jtable = new javax.swing.JTable();
        Refresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search_feild = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Coach Mengament");

        EC_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academy_football_systeme/icons8_exit_16.png"))); // NOI18N
        EC_B.setText("Exit");
        EC_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EC_BActionPerformed(evt);
            }
        });

        AC_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academy_football_systeme/icons8_plus_16.png"))); // NOI18N
        AC_B.setText("Add Coach");
        AC_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC_BActionPerformed(evt);
            }
        });

        C_Jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", " Name", "Phone Number", "Adresse", "Sex", "Date Of Startiing Training", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        C_Jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C_JtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(C_Jtable);

        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academy_football_systeme/icons8_refresh_16.png"))); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("List Of Coaches:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Value To Search:");

        search_feild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_feildKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(AC_B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Refresh)
                .addGap(151, 151, 151)
                .addComponent(EC_B)
                .addGap(17, 17, 17))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(search_feild, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(search_feild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AC_B)
                    .addComponent(EC_B)
                    .addComponent(Refresh)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EC_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EC_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EC_BActionPerformed

    private void AC_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC_BActionPerformed
        // TODO add your handling code here:
        Add_Coach AC=new Add_Coach();
        AC.setVisible(true);
        AC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_AC_BActionPerformed

    private void C_JtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_JtableMouseClicked
        // TODO add your handling code here:
        
        int what_row=C_Jtable.getSelectedRow();
       
        
        int idd=(int) C_Jtable.getValueAt(what_row,0);
        String fname=C_Jtable.getValueAt(what_row, 1).toString();
        String phone=C_Jtable.getValueAt(what_row, 2).toString();
        String adress=C_Jtable.getValueAt(what_row, 3).toString();
        
        String sex=C_Jtable.getValueAt(what_row, 4).toString();
        String dateofstarting=C_Jtable.getValueAt(what_row, 5).toString();
      String email=C_Jtable.getValueAt(what_row, 6).toString();
        Update_Coach UC=new Update_Coach(idd,fname,phone,adress,sex,dateofstarting,email);
        UC.setVisible(true);
        UC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        
        
        
        
        
    }//GEN-LAST:event_C_JtableMouseClicked

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        
         Connection con = null;
String url ="jdbc:sqlserver://localhost:1433;databaseName=academy_football_systeme;integratedSecurity=true;";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Coach_Mengament.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            con =DriverManager.getConnection(url);
            if(con!=null)
            {
                                        String query="select * from Coach ";
                         
                         Statement st = con.createStatement();
                            ResultSet rs = st.executeQuery(query);
                         
        dm = (DefaultTableModel) C_Jtable.getModel();
        dm.setRowCount(0);
        while(rs.next())
        {
        dm.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),rs.getString(6),rs.getString(7)});
        }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Coach_Mengament.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
        
    }//GEN-LAST:event_RefreshActionPerformed

    private void search_feildKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_feildKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table=(DefaultTableModel) C_Jtable.getModel();
            String searchh =search_feild.getText().toString();
            TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(table);
            
            C_Jtable.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(searchh));
    }//GEN-LAST:event_search_feildKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coach_Mengament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coach_Mengament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coach_Mengament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coach_Mengament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coach_Mengament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC_B;
    private javax.swing.JTable C_Jtable;
    private javax.swing.JButton EC_B;
    private javax.swing.JButton Refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search_feild;
    // End of variables declaration//GEN-END:variables
}
