/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academy_football_systeme;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author fcss
 */
public class Update_Coach extends javax.swing.JFrame {

    /**
     * Creates new form Update_Coach
     */
    public Update_Coach() {
        initComponents();
          this.setLocationRelativeTo(null);// center form in the screen
          ImageIcon ic= new ImageIcon("C:\\Users\\fcss\\Desktop\\projet_gui\\Academy_Football_Systeme\\src\\academy_football_systeme\\soccer_ball_26px.png");
     this.setIconImage(ic.getImage());
     
      this.setTitle("Update Coach");
  
    }
    
   public Update_Coach(int id_c,String fname,String phonenb,String adress,String sex,String dateofsarting,String email)
    {
        initComponents();
        String ss=Integer.toString(id_c);
        ID_C.setText(ss);
        FN_C.setText(fname);
        PH_C.setText(phonenb);
        AD_C.setText(adress);
        if(sex.equals("Male"))
        {S_M_C.setSelected(true);}
        if(sex.equals("Female"))
        {S_F_C.setSelected(true);}
        DT_C.setText(dateofsarting);
        Email.setText(email);
           
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CC_B = new javax.swing.JButton();
        AC_B = new javax.swing.JButton();
        FN_C = new javax.swing.JTextField();
        S_M_C = new javax.swing.JRadioButton();
        S_F_C = new javax.swing.JRadioButton();
        AD_C = new javax.swing.JTextField();
        DT_C = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PH_C = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ID_C = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Coach");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sex");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adresse");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date Of Starting Training");

        CC_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academy_football_systeme/icons8_delete_16.png"))); // NOI18N
        CC_B.setText("Delete");
        CC_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CC_BActionPerformed(evt);
            }
        });

        AC_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academy_football_systeme/icons8_plus_16.png"))); // NOI18N
        AC_B.setText("Update");
        AC_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC_BActionPerformed(evt);
            }
        });

        FN_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FN_CActionPerformed(evt);
            }
        });

        S_M_C.setForeground(new java.awt.Color(255, 255, 255));
        S_M_C.setText("Male");
        S_M_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_M_CActionPerformed(evt);
            }
        });

        S_F_C.setForeground(new java.awt.Color(255, 255, 255));
        S_F_C.setText("Female");

        AD_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AD_CActionPerformed(evt);
            }
        });

        DT_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DT_CActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID:");

        ID_C.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ID_C.setForeground(new java.awt.Color(255, 255, 255));
        ID_C.setText("id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(CC_B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AC_B)
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DT_C)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(50, 50, 50)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AD_C, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(S_M_C)
                                        .addGap(18, 18, 18)
                                        .addComponent(S_F_C)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID_C)
                                    .addComponent(FN_C, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PH_C, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ID_C))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FN_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(PH_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(AD_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(S_M_C)
                    .addComponent(S_F_C))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(DT_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CC_B)
                    .addComponent(AC_B))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AC_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC_BActionPerformed
        // TODO add your handling code here:
        
        Update_Coach();

        
    }//GEN-LAST:event_AC_BActionPerformed

    private void FN_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FN_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FN_CActionPerformed

    private void S_M_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_M_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_M_CActionPerformed

    private void AD_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AD_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AD_CActionPerformed

    private void DT_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DT_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DT_CActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void CC_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CC_BActionPerformed
 // TODO add your handling code here:
        
        
        Delete_coach();
    }//GEN-LAST:event_CC_BActionPerformed

    
    
    public void Delete_coach()
    {
        Connection con = null;
String url ="jdbc:sqlserver://localhost:1433;databaseName=academy_football_systeme;integratedSecurity=true;";
try {
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
con =DriverManager.getConnection(url);
if(con!=null)
{
    int idplayer=Integer.parseInt(ID_C.getText().toString());
  
    
 String query = "delete from Coach where Coach.COACH_ID="+idplayer ;
Statement st = con.createStatement();
//ResultSet rs = st.executeQuery(query);
st.executeUpdate(query);
JOptionPane.showMessageDialog(null,"the coach with id "+idplayer+" is deleted !!");  

}
} catch (SQLException ex) {
JOptionPane.showMessageDialog(null,"Impossible to read data" + ex.toString());

}       catch (ClassNotFoundException ex) {
            Logger.getLogger(Update_Player.class.getName()).log(Level.SEVERE, null, ex);
        }
finally{
if(con!=null) 
try {
    con.close();
} catch (SQLException ex) {
    Logger.getLogger(Update_Player.class.getName()).log(Level.SEVERE, null, ex);
}
}
    }
    
    
    
    
    
    
    
    public void Update_Coach()
{
       Connection con = null;
String url ="jdbc:sqlserver://localhost:1433;databaseName=academy_football_systeme;integratedSecurity=true;";
try {
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

con =DriverManager.getConnection(url);
if(con!=null)
{
  
    int idplayer=Integer.parseInt(ID_C.getText().toString());
    String fname=FN_C.getText().toString();
    String phone=PH_C.getText().toString();
    String adress=AD_C.getText().toString();
    String sex=null;
    if(S_M_C.isSelected()){sex="Male";}
    if(S_F_C.isSelected()){sex="Female";}
    
    String dateofstarting=DT_C.getText().toString();
String email=Email.getText().toString();
//String query = "update Player set Player.FIRST_NAME='"+fname+"','Player.LAST_NAME="+lname+", Player.DATE_OF_BIRTHDAY="+dateofbirth+", Player.BLOOD_TYPE="+bloodtype+", Player.POSITION="+pos+", Player.SEX="+sex+", Player.ADRESSE="+adress+", Player.DATE_OF_REGESTRATION="+ dateofreg+", Player.DESCRIPTIONS="+desc+"where Player.PLAYER_ID="+idplayer;

 String query2="update Coach set NAME='"+fname+"',PHONE_NUMBER='"+phone+"',ADRESSE='"+adress+"',SEX='"+sex+"',DATE_OF_STARTING_TRAINIG='"+dateofstarting+"',EMAIL='"+email+"'where COACH_ID="+idplayer; 
  Statement st = con.createStatement();
//ResultSet rs = st.executeQuery(query);
st.executeUpdate(query2);
JOptionPane.showMessageDialog(null,"the coach with id : "+idplayer+" has been updated!");  


}
} catch (SQLException ex) {
JOptionPane.showMessageDialog(null,"Impossible to read data" + ex.toString());
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(Update_Player.class.getName()).log(Level.SEVERE, null, ex);
        }
finally{
if(con!=null) 
try {
    con.close();
} catch (SQLException ex) {
    Logger.getLogger(Update_Player.class.getName()).log(Level.SEVERE, null, ex);
}
}
    
}
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Coach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC_B;
    private javax.swing.JTextField AD_C;
    private javax.swing.JButton CC_B;
    private javax.swing.JTextField DT_C;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FN_C;
    private javax.swing.JLabel ID_C;
    private javax.swing.JTextField PH_C;
    private javax.swing.JRadioButton S_F_C;
    private javax.swing.JRadioButton S_M_C;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
