/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academy_football_systeme;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author fcss
 */
public class Update_Player extends javax.swing.JFrame {

    /**
     * Creates new form Update_Player
     */
    public Update_Player() {
        initComponents();
          this.setLocationRelativeTo(null);// center form in the screen
          ImageIcon ic= new ImageIcon("C:\\Users\\fcss\\Desktop\\projet_gui\\Academy_Football_Systeme\\src\\academy_football_systeme\\soccer_ball_26px.png");
     this.setIconImage(ic.getImage());
   this.setTitle("Update Player");
    }
    
    public Update_Player(int id,String fname,String dateofbirth,String phonenb,String adress,String blodtype,String pos,String sex,String dateofReg,String Desc)
    {
        initComponents();
        this.setLocationRelativeTo(null);
        
        String ss=Integer.toString(id);
       

     // randor
       
       
        id_player.setText(ss);
        FN_P.setText(fname);
        DB_P.setText(dateofbirth);
        PH_P.setText(phonenb);
        AD_P.setText(adress);
        BT_P.setSelectedItem(blodtype);
        PO_P.setSelectedItem(pos);
        if(sex.equals("Male"))
        {S_M_P.setSelected(true);
         S_F_P.setSelected(false);
        }
        if(sex.equals("Female"))
        {S_F_P.setSelected(true);
        S_M_P.setSelected(false);
        }
        DR_P.setText( dateofReg);
        DES_P.setText(Desc);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        C_B = new javax.swing.JButton();
        AP_B = new javax.swing.JButton();
        FN_P = new javax.swing.JTextField();
        PH_P = new javax.swing.JTextField();
        DB_P = new javax.swing.JTextField();
        S_M_P = new javax.swing.JRadioButton();
        S_F_P = new javax.swing.JRadioButton();
        DR_P = new javax.swing.JTextField();
        BT_P = new javax.swing.JComboBox<>();
        PO_P = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        DES_P = new javax.swing.JTextField();
        AD_P = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        id_player = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Player");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone Number :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date Of Birthday");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Blood Type");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Position");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sex");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adresse");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date Of Registration");

        C_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academy_football_systeme/icons8_delete_16.png"))); // NOI18N
        C_B.setText("Delete Player");
        C_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_BActionPerformed(evt);
            }
        });

        AP_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academy_football_systeme/icons8_plus_16.png"))); // NOI18N
        AP_B.setText("Update Player");
        AP_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AP_BActionPerformed(evt);
            }
        });

        FN_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FN_PActionPerformed(evt);
            }
        });

        buttonGroup1.add(S_M_P);
        S_M_P.setForeground(new java.awt.Color(255, 255, 255));
        S_M_P.setText("Male");
        S_M_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_M_PActionPerformed(evt);
            }
        });

        buttonGroup1.add(S_F_P);
        S_F_P.setForeground(new java.awt.Color(255, 255, 255));
        S_F_P.setText("Female");

        BT_P.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-","AB+","AB-","O+","O-"}));
        BT_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_PActionPerformed(evt);
            }
        });

        PO_P.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "goalkeeper", "defender", "Midfielder", "Attacker" }));
        PO_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_PActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Description");

        AD_P.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID Player :");

        id_player.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        id_player.setForeground(new java.awt.Color(255, 255, 255));
        id_player.setText("id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(C_B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AP_B))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(id_player))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(DB_P, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                .addComponent(PH_P)
                                                .addComponent(FN_P))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(S_M_P)
                                                    .addComponent(AD_P, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(118, 118, 118)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BT_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PO_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(53, 53, 53))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DR_P, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DES_P, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(S_F_P)
                            .addComponent(jLabel1))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(id_player))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FN_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(DB_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PH_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(AD_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(BT_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PO_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(S_M_P)
                    .addComponent(S_F_P))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DR_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DES_P, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_B)
                    .addComponent(AP_B))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void delete_palyer()
    {
        
        
Connection con = null;
String url ="jdbc:sqlserver://localhost:1433;databaseName=academy_football_systeme;integratedSecurity=true;";
try {
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
con =DriverManager.getConnection(url);
if(con!=null)
{
    int idplayer=Integer.parseInt(id_player.getText().toString());
  
    
 String query = "delete from Player where Player.PLAYER_ID="+idplayer ;
Statement st = con.createStatement();
//ResultSet rs = st.executeQuery(query);
st.executeUpdate(query);
JOptionPane.showMessageDialog(null,"the student with id "+idplayer+" is deleted !!");  

}
} catch (SQLException ex) {
JOptionPane.showMessageDialog(null,"Impossible to read data" + ex.toString());

}       catch (ClassNotFoundException ex) {
            Logger.getLogger(Update_Player.class.getName()).log(Level.SEVERE, null, ex);
        }
finally{
if(con!=null) 
try {
    con.close();
} catch (SQLException ex) {
    Logger.getLogger(Update_Player.class.getName()).log(Level.SEVERE, null, ex);
}
}
 }
  
  

    
   public void update_player()
   {
       Connection con = null;
String url ="jdbc:sqlserver://localhost:1433;databaseName=academy_football_systeme;integratedSecurity=true;";
try {
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

con =DriverManager.getConnection(url);
if(con!=null)
{
  
    int idplayer=Integer.parseInt(id_player.getText().toString());
    String fname=FN_P.getText().toString();
    String dateofbirth=DB_P.getText();
    String phonenb=PH_P.getText().toString();
    String adress=AD_P.getText().toString();
    String bloodtype=BT_P.getSelectedItem().toString();
    String pos=PO_P.getSelectedItem().toString();
    String sex=null;
    if(S_M_P.isSelected()){sex="Male";}
    if(S_F_P.isSelected()){sex="Female";}
    String dateofreg=DR_P.getText().toString();
    String desc=DES_P.getText().toString();
    
  //String query = "update Player set Player.FIRST_NAME='"+fname+"','Player.LAST_NAME="+lname+", Player.DATE_OF_BIRTHDAY="+dateofbirth+", Player.BLOOD_TYPE="+bloodtype+", Player.POSITION="+pos+", Player.SEX="+sex+", Player.ADRESSE="+adress+", Player.DATE_OF_REGESTRATION="+ dateofreg+", Player.DESCRIPTIONS="+desc+"where Player.PLAYER_ID="+idplayer;

 String query2="update Player set NAME='"+fname+"',DATE_OF_BIRTHDAY='"+dateofbirth+"',PHONE_NUMBER='"+phonenb+"',ADRESSE='"+adress+"',BLOOD_TYPE='"+bloodtype+"',POSITION='"+pos+"',SEX='"+sex+"',DATE_OF_REGESTRATION='"+dateofreg+"',DESCRIPTIONS='"+desc+"' where PLAYER_ID="+idplayer; 
  Statement st = con.createStatement();
//ResultSet rs = st.executeQuery(query);
st.executeUpdate(query2);
JOptionPane.showMessageDialog(null,"the student with id "+ idplayer+" has benen updated!");  


}
} catch (SQLException ex) {
JOptionPane.showMessageDialog(null,"Impossible to read data" + ex.toString());
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(Update_Player.class.getName()).log(Level.SEVERE, null, ex);
        }
finally{
if(con!=null) 
try {
    con.close();
} catch (SQLException ex) {
    Logger.getLogger(Update_Player.class.getName()).log(Level.SEVERE, null, ex);
}
}
       
       
   }
   
    
    
    
    private void FN_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FN_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FN_PActionPerformed

    private void S_M_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_M_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_M_PActionPerformed

    private void BT_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_PActionPerformed

    private void PO_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PO_PActionPerformed

    private void AP_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AP_BActionPerformed
        // TODO add your handling code here:
        update_player();
    }//GEN-LAST:event_AP_BActionPerformed

    private void C_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_BActionPerformed
        // TODO add your handling code here:
        delete_palyer();
    }//GEN-LAST:event_C_BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Player().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AD_P;
    private javax.swing.JButton AP_B;
    private javax.swing.JComboBox<String> BT_P;
    private javax.swing.JButton C_B;
    private javax.swing.JTextField DB_P;
    private javax.swing.JTextField DES_P;
    private javax.swing.JTextField DR_P;
    private javax.swing.JTextField FN_P;
    private javax.swing.JTextField PH_P;
    private javax.swing.JComboBox<String> PO_P;
    private javax.swing.JRadioButton S_F_P;
    private javax.swing.JRadioButton S_M_P;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel id_player;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
